#!/bin/bash
#
# rotsix - (c) wtfpl 2016
# a small script to manage simply some easy tasks as volume or backlight


usage () {
	echo -e "${0}"
	echo -e "Simple Task Manager"
	echo -e "  usage : "
	echo -e "    $(basename $0) backlight|bl +|-|up|down|get [value]"
	echo -e "    $(basename $0) vol|volume|v +|-|up|toggle|down [value]"
	echo -e "    $(basename $0) bluetooth|bt start|up|stop|kill|restart|on|off|down"
	echo -e "    $(basename $0) mysql|sql|sqld|mysqld start|up|stop|kill|restart|on|stop|off"
	echo -e "    $(basename $0) http|httpd start|up|stop|kill|restart|on|stop|off"
	echo -e "    $(basename $0) lamp|LAMP start|up|stop|kill|restart|on|stop|off"
}


if [ -z "$1" ]; then
	echo "$(usage)"
	exit 1
fi

if [ -z "$2" -a "$1" != "help" -a "$1" != "h" -a "$1" != "-h" -a "$1" != "--help" ]; then
	echo "$(usage)"
	exit 1
fi

case $1 in
	help|h|-h|--help)
		echo "$(usage)"
		exit 0
		;;
	vol|volume|v)
		# card name can be obtained via `pactl list sinks`
		card="alsa_output.pci-0000_00_1b.0.analog-stereo"
		test -n "$3" && perc="$3" || perc="5"
		case $2 in
			up|+)
				aplay $HOME/.config/i3/audio-volume-change.wav
				pactl set-sink-mute "${card}" false
				pactl set-sink-volume "${card}" +${perc}%
				;;
			toggle)
				pactl set-sink-mute ${card} toggle
				aplay $HOME/.config/i3/audio-volume-change.wav
				;;
			down|-)
				aplay $HOME/.config/i3/audio-volume-change.wav
				pactl set-sink-mute "${card}" false
				pactl set-sink-volume "${card}" -${perc}%
				;;
			*)
				echo "$(usage)"
				exit 1
				;;
		esac
		;;
	backlight|bl)
		test -n "$3" && perc="$3" || perc="5"
		#actual="$(brightnessctl get | grep "Current" | cut -d '(' -f 2 | cut -d '%' -f 1)"
		case $2 in
			+|up)
				brightnessctl set "$perc"%+
				;;
			-|down)
				brightnessctl set "$perc"%-
				;;
			get)
				brightnessctl get
				;;
			*)
				echo "$(usage)"
				exit 1
				;;
		esac
		;;
	bluetooth|bt)
		case $2 in
			up|start|on)
				sudo systemctl start bluetooth
				echo "Bluetooth started"
				;;
			stop|kill|down|off)
				sudo systemctl stop bluetooth
				echo "Bluetooth stopped"
				;;
			restart)
				sudo systemctl restart bluetooth
				echo "Bluetooth restarted"
				;;
			*)
				echo "$(usage)"
				exit 1
				;;
		esac
		;;

	mysql|sql|mysqld|sqld)
		case $2 in
			up|start|on)
				sudo systemctl start mysqld
				echo "MySQL daemon started"
				;;
			stop|kill|down|off)
				sudo systemctl stop mysqld
				echo "MySQL daemon stopped"
				;;
			restart)
				sudo systemctl restart mysqld
				echo "MySQL daemon restarted"
				;;
			*)
				echo "$(usage)"
				exit 1
				;;
		esac
		;;
	
	http|httpd)
		case $2 in
			up|start|on)
				sudo systemctl start httpd
				echo "HTTP daemon started"
				;;
			stop|kill|down|off)
				sudo systemctl stop httpd
				echo "HTTP daemon stopped"
				;;
			restart)
				sudo systemctl restart httpd
				echo "HTTP daemon restarted"
				;;
			*)
				echo "$(usage)"
				exit 1
				;;
		esac
		;;

	lamp|LAMP)
		case $2 in
			up|start|on)
				stm sql start
				stm http start
				;;
			stop|kill|down|off)
				stm sql stop
				stm http stop
				;;
			restart)
				stm sql restart
				stm httm restart
				;;
			*)
				echo "$(usage)"
				exit 1
				;;
		esac
		;;
	*)
		echo "$(usage)"
		exit 1
		;;
esac

exit 0
