#!/usr/bin/env bash
#
# rotsix - (c) wtfpl 2017
# simple theme manager

usage () {
  echo "$0"
  echo "usage: $(basename "$0") <theme>"
}


files=(termite wallpaper polybar volumeicon gtk-icon vim dunst)


set_theme () {
  for i in "${files[@]}"; do
    case "$i" in
      termite)
        cp -- "$HOME/.config/termite/config.$1" "$HOME/.config/termite/config"
        ;;
      wallpaper)
        cp -- "$HOME/.wallpaper.$1.png" "$HOME/.wallpaper.png"
        ;;
      polybar)
      	case "$1" in
      	  light)
      	  	sed -Ei 's/^background = #[a-fA-F0-9]{6}$/background = #fbf4e1/g' "$HOME/.config/polybar/config"
      	  	sed -Ei 's/^foreground = #[a-fA-F0-9]{6}$/foreground = #073642/g' "$HOME/.config/polybar/config"
      	  	sed -Ei 's/^selected = #[a-fA-F0-9]{6}$/selected = #000000/g' "$HOME/.config/polybar/config"
      	  	;;
      	  dark)
      	  	sed -Ei 's/^background = #[a-fA-F0-9]{6}$/background = #15191B/g' "$HOME/.config/polybar/config"
      	  	sed -Ei 's/^foreground = #[a-fA-F0-9]{6}$/foreground = #a6a6a6/g' "$HOME/.config/polybar/config"
      	  	sed -Ei 's/^selected = #[a-fA-F0-9]{6}$/selected = #FFFFFF/g' "$HOME/.config/polybar/config"
      	  	;;
      	  *)
      	  	echo "This theme isn't supported, add it in set_theme() for polybar"
      	  	exit 1
      	  	;;
      	esac
      	;;
      volumeicon)
      	cp -- "$HOME/.config/volumeicon/volumeicon.$1" "$HOME/.config/volumeicon/volumeicon"
      	;;
      gtk-icon)
      	case "$1" in
      	  light)
      	   	sed -Ei 's/^gtk-icon-theme-name=.*$/gtk-icon-theme-name=Numix-Circle-Light/' "$HOME/.config/gtk-3.0/settings.ini"
      	  	;;
      	  dark)
      	  	sed -Ei 's/^gtk-icon-theme-name=.*$/gtk-icon-theme-name=Numix-Circle/' "$HOME/.config/gtk-3.0/settings.ini"
      	  	;;
      	  *)
      	  	echo "This theme isn't supported, add it in set_theme() for gtk-icon"
      	  	exit 1
      	  	;;
      	esac
      	;;
      vim)
      	case "$1" in
		  light)
		  	sed -Ei 's/^colorscheme .*$/colorscheme seoul256-light/' "$HOME/.config/nvim/init.vim"
		  	sed -Ei "s/^\\ 'colorscheme': '.*',$/\\ 'colorscheme': 'solarized',/" "$HOME/.config/nvim/init.vim"
		  	;;
		  dark)
		  	sed -Ei 's/^colorscheme .*$/colorscheme brogrammer/' "$HOME/.config/nvim/init.vim"
		  	sed -Ei "s/^\\ 'colorscheme': '.*',$/\\ 'colorscheme': 'wombat',/" "$HOME/.config/nvim/init.vim"
		  	;;
      	  *)
      	  	echo "This theme isn't supported, add it in set_theme() for gtk-icon"
      	  	exit 1
      	  	;;
      	esac
      	;;
      dunst)
      	case "$1" in
      	  light)
			sed -Ei 's/^background = "#[0-9a-fA-F]{6}"$/background = "#FDF6E3"/g' "$HOME/.config/dunst/dunstrc"
			sed -Ei 's/^foreground = "#[0-9a-fA-F]{6}"$/foreground = "#073642"/g' "$HOME/.config/dunst/dunstrc"
      	  	;;
      	  dark)
			sed -Ei 's/^background = "#[0-9a-fA-F]{6}"$/background = "#15191B"/g' "$HOME/.config/dunst/dunstrc"
			sed -Ei 's/^foreground = "#[0-9a-fA-F]{6}"$/foreground = "#a6a6a6"/g' "$HOME/.config/dunst/dunstrc"
      	  	;;
      	  *)
      	  	echo "This theme isn't supported, add it in set_theme() for gtk-icon"
      	  	exit 1
      	  	;;
      	esac
      	;;
      *)
        echo "This option isn't supported, add it in set_theme()"
        exit 1
        ;;
    esac
  done
}


reload () {
  for i in "${files[@]}"; do
    case $i in
      termite)
        pkill -10 termite
        ;;
      wallpaper)
        hsetroot -center "$HOME/.wallpaper.png"
        ;;
      polybar)
      	pkill -10 polybar
      	;;
      volumeicon)
      	killall -q volumeicon 
      	while pgrep -x volumeicon > /dev/null; do sleep .1; done
      	volumeicon &> /dev/null &
      	;;
      gtk-icon)
      	# nm-applet
      	killall -q nm-applet
      	while pgrep -x nm-applet > /dev/null; do sleep .1; done
      	nm-applet &> /dev/null &
      	;;
      vim)
      	;;
      dunst)
      	killall -q dunst
      	while pgrep -x dunst > /dev/null; do sleep .1; done
      	dunst &> /dev/null &
      	;;
      *)
        echo "This option isn't supported, add it in reload()"
        exit 1
        ;;
    esac
  done
}


test -z "$1" && usage && exit 0

case $1 in
  help|-h|--help)
  	usage
  	exit 0
  	;;
  light)
  	set_theme light
  	reload
  	;;
  dark)
  	set_theme dark
  	reload
  	;;
  *)
  	echo "This theme is not set, modify the script to add it."
  	exit 0
  	;;
esac
