#!/usr/bin/env bash
#
# rotsix - (c) wtfpl 2017
# simple theme manager

usage () {
  echo "$0"
  echo "usage: $(basename "$0") <theme>"
}


# suggestions: wallpaper, gtk-theme
files=(termite vim)


set_theme () {
  for i in "${files[@]}"; do
    case "$i" in
      termite)
        case "$1" in
          light)
            sed -Ei -e 's/^background = #[a-fA-F0-9]{6}$/background = #ffffff/g' \
              -e 's/^foreground = #[a-fA-F0-9]{6}$/foreground = #24292e/g' \
              -e 's/^color0 = #[a-fA-F0-9]{6}$/color0 = #babbbc/g' \
              -e 's/^color8 = #[a-fA-F0-9]{6}$/color8 = #76787b/g' \
              -e 's/^color1 = #[a-fA-F0-9]{6}$/color1 = #d7a349/g' \
              -e 's/^color9 = #[a-fA-F0-9]{6}$/color9 = #b31d28/g' \
              -e 's/^color2 = #[a-fA-F0-9]{6}$/color2 = #3ebc5c/g' \
              -e 's/^color10 = #[a-fA-F0-9]{6}$/color10 = #22863a/g' \
              -e 's/^color3 = #[a-fA-F0-9]{6}$/color3 = #f18338/g' \
              -e 's/^color11 = #[a-fA-F0-9]{6}$/color11 = #e36209/g' \
              -e 's/^color4 = #[a-fA-F0-9]{6}$/color4 = #005cc5/g' \
              -e 's/^color12 = #[a-fA-F0-9]{6}$/color12 = #032f62/g' \
              -e 's/^color5 = #[a-fA-F0-9]{6}$/color5 = #6f42c1/g' \
              -e 's/^color13 = #[a-fA-F0-9]{6}$/color13 = #45267d/g' \
              -e 's/^color6 = #[a-fA-F0-9]{6}$/color6 = #005cc5/g' \
              -e 's/^color14 = #[a-fA-F0-9]{6}$/color14 = #032f62/g' \
              -e 's/^color7 = #[a-fA-F0-9]{6}$/color7 = #41484f/g' \
              -e 's/^color15 = #[a-fA-F0-9]{6}$/color15 = #24292e/g' \
              "$HOME/.config/termite/config"
            ;;
          dark)
            sed -Ei -e 's/^background = #[a-fA-F0-9]{6}$/background = #000000/g' \
              -e 's/^foreground = #[a-fA-F0-9]{6}$/foreground = #f5f5f5/g' \
              -e 's/^color0 = #[a-fA-F0-9]{6}$/color0 = #000000/g' \
              -e 's/^color8 = #[a-fA-F0-9]{6}$/color8 = #909090/g' \
              -e 's/^color1 = #[a-fA-F0-9]{6}$/color1 = #d61d15/g' \
              -e 's/^color9 = #[a-fA-F0-9]{6}$/color9 = #f00f05/g' \
              -e 's/^color2 = #[a-fA-F0-9]{6}$/color2 = #98971a/g' \
              -e 's/^color10 = #[a-fA-F0-9]{6}$/color10 = #b8bb26/g' \
              -e 's/^color3 = #[a-fA-F0-9]{6}$/color3 = #d79921/g' \
              -e 's/^color11 = #[a-fA-F0-9]{6}$/color11 = #fabd2f/g' \
              -e 's/^color4 = #[a-fA-F0-9]{6}$/color4 = #458588/g' \
              -e 's/^color12 = #[a-fA-F0-9]{6}$/color12 = #83a598/g' \
              -e 's/^color5 = #[a-fA-F0-9]{6}$/color5 = #b16286/g' \
              -e 's/^color13 = #[a-fA-F0-9]{6}$/color13 = #d3869b/g' \
              -e 's/^color6 = #[a-fA-F0-9]{6}$/color6 = #689d6a/g' \
              -e 's/^color14 = #[a-fA-F0-9]{6}$/color14 = #8ec07c/g' \
              -e 's/^color7 = #[a-fA-F0-9]{6}$/color7 = #d8d8d8/g' \
              -e 's/^color15 = #[a-fA-F0-9]{6}$/color15 = #f9e5d1/g' \
              "$HOME/.config/termite/config"
            ;;
          *)
            echo "This theme isn't supported, add it in set_theme() for termite"
            exit 1
            ;;
        esac
        ;;
      vim)
      	case "$1" in
	        light)
	          sed -Ei -e 's/^colorscheme .*$/colorscheme github/g' \
	            "$HOME/.config/nvim/init.vim"
	          ;;
	        dark)
	          sed -Ei -e 's/^colorscheme .*$/colorscheme newbz/g' \
	            "$HOME/.config/nvim/init.vim"
	          ;;
      	  *)
      	    echo "This theme isn't supported, add it in set_theme() for '$1'"
      	    exit 1
      	    ;;
      	esac
      	;;
      *)
        echo "This application isn't supported, add it in set_theme()"
        exit 1
        ;;
    esac
  done
}


reload () {
  for i in "${files[@]}"; do
    case $i in
      termite)
        pkill -10 termite
        ;;
      vim)
        themer.neovim.py
        ;;
      *)
        echo "This option isn't supported, add it in reload()"
        exit 1
        ;;
    esac
  done
}


test -z "$1" && usage && exit 0

case $1 in
  help|-h|--help)
    usage
    exit 0
    ;;
  light)
    set_theme light
    reload
    ;;
  dark)
    set_theme dark
    reload
    ;;
  *)
    echo "This theme is not set, modify the script to add it."
    exit 0
    ;;
esac

# vim: sw=2: ts=2:
