#!/usr/bin/env bash
#
# rotsix - (c) wtfpl 2017
# small theme manager

usage(){
	echo -e "${0}"
	echo -e "Small theme manager"
	echo -e " usage:"
	echo -e " $(basename $0) <theme>"
}

termite(){
	rm -rf "${HOME}"/.config/termite/config
	cp "${HOME}"/.config/termite/config."$1" "${HOME}"/.config/termite/config
}

if [ -z "$1" ]; then
	usage
	exit 1
fi

case "$1" in
	light)
		termite light
		exit 0
		;;
	dark)
		termite dark
		exit 0
		;;
	*)
		usage
		echo -e "\nThis theme (${1}) is not set, create it by modifying this script."
		exit 1
		;;
esac
